name: CI

on:
  push:
    branches: [ main ]
	
jobs:
  integrationTests:
    runs-on: ubuntu-latest
	steps:
	  - uses: actions/checkout@v2
	  - run: npm install &
	  - nun: npx newman tests/integration-v1.json